name: Download ppmod.nut into every package

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Find all vscripts folders and download ppmod.nut
        run: |
          find packages -type d -path "*/sources/scripts/vscripts" | while read dir; do
            echo "Downloading ppmod.nut to $dir"
            curl -Ls "https://raw.githubusercontent.com/p2r3/ppmod/main/ppmod.nut" -o "$dir/ppmod.nut"
          done

      - name: Commit & push if anything changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add packages
          git diff --cached --quiet || git commit -m "Update ppmod.nut in all packages"
          git push
